# Generated by Django 5.2.7 on 2025-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
