# Generated by Django 5.2.7 on 2025-10-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('genre', models.CharField(default='customer', max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.FileField(blank=True, upload_to='uploads/thumbnails')),
                ('url', models.FileField(upload_to='uploads/videos/originals')),
                ('is_converted', models.BooleanField(default=False)),
                ('current_convert_state', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentVideoConvertProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_convert_progress', to='service_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_time', models.FloatField()),
                ('is_finished', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.video')),
            ],
        ),
    ]
