# Generated by Django 5.2.7 on 2025-10-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='headline',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='', max_length=65),
        ),
    ]
