# Generated by Django 5.2.7 on 2025-10-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_rename_thumbnail_video_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprogress',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='current_convert_state',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_converted',
        ),
        migrations.DeleteModel(
            name='CurrentVideoConvertProgress',
        ),
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
